version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: ./devops/php.dockerfile
    restart: unless-stopped
    volumes:
      - ../:/var/www/html
    depends_on:
      - postgres
      - redis
      - mailhog
  nginx:
    build:
      context: ..
      dockerfile: ./devops/nginx.dockerfile
    ports:
      - "9000:80"
    volumes:
      - ../:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - postgres
  postgres:
    image: postgres:16-alpine
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
  mailhog:
    image: mailhog/mailhog
    container_name: laravel_mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"
  composer:
    build:
      context: ..
      dockerfile: ./devops/composer.dockerfile
    volumes:
      - ../:/var/www/html


  pgadmin:
      image: dpage/pgadmin4:latest
      container_name: pgadmin
      restart: unless-stopped
      depends_on:
          - postgres
      environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: secret
      ports:
          - "127.0.0.1:8082:80"


volumes:
  postgres_data:
